version: '2'
services:
  fpm:
    image: php:7-fpm
    volumes:
      - .:/address-jockey
    links:
      - mysql
    env_file: phinx.env
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/site.conf
      - .:/address-jockey
    links:
      - fpm
  mysql:
    image: mysql:5.7
    env_file: mysql.env
